queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=1"
    merge_conditions:
      - check-success=build
      - check-success=DeepScan
    merge_method: squash

pull_request_rules:
  - name: automatic branch update
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
    actions:
      update: {}
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: Automatic merge on approval
    conditions: []
    actions:
      queue:
