approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmPreapprovedPackages:
  - "@openforis/arena-core"

npmScopes:
  openforis:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.16.0.cjs
