name: Run yarn test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.15.0
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
      - run: yarn
      - run: yarn test
