name: Run yarn test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.15.0
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
          always-auth: true
          auth-token: ${{secrets.ACCESS_TOKEN}}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@openforis'
        env:
            NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            NPM_REGISTRY_URL: https://npm.pkg.github.com
      - run: yarn
      - run: yarn test
