name: Run yarn test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.15.0
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
          always-auth: true
          registry-url: 'https://npm.pkg.github.com'
          auth-token: ${{secrets.ACCESS_TOKEN}}
        env:
            NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            NPM_REGISTRY_URL: https://npm.pkg.github.com
      - name: Create NPMRC
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" > ~/.npmrc
      - run: yarn
      - run: yarn test
