name: Run yarn test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:12-3.0
        env:
          POSTGRES_USER: arena
          POSTGRES_PASSWORD: arena
          POSTGRES_DB: arena
        ports:
          - 5444:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.15.0
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
          always-auth: true
          auth-token: ${{secrets.ACCESS_TOKEN}}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@openforis'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_REGISTRY_URL: https://npm.pkg.github.com
      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_REGISTRY_URL: https://npm.pkg.github.com
      - run: yarn test
        env:
          PGHOST: localhost
          PGPORT: 5444
          PGDATABASE: arena
          PGUSER: arena
          PGPASSWORD: arena
